### PR TITLE
Revised MyBasicMusicBox

### PR DESCRIPTION
**Pull request by csivek**
Revised MyBasicMusicBox to use FMOD implementations. Brought over only Cryptique and Masquerade songs

### CODE REVIEW

**Comment by csivek** [comment]
Just throw away my .uproject file and keep the original. I did add FMOD as a plugin so if it automatically add itself we need to make sure to remove it (or put FMOD on everyone's computers)

**Comment by BigDub** [comment]
Hmm, seven hours before I noticed this. That is not fast enough. I wonder if there is an easy way to push to my phone. I am going to look over this real quick.

**Comment by BigDub** [comment]
We can easily add the FMOD plugin to the .uproject file and mark it as disabled and it will not bother everyone every time they open the project nor will it add itself every time a computer that does has it touches it. The issue is that this branch now has code in execution that requires the FMOD plugin. This means trying to play the game will crash every time without exception.
This is not acceptable.
We need to decide what we want to do with the FMOD plugin. If we're going to use it then I believe we do need it installed on every computer in the lab. There are alternatives, but they are messy.
Currently I am in favor of simply installing it on all the machines, but I do not know exactly what this entails. How large is the FMOD plugin? It may be feasible to simply have the CSRs add it to the lab machines' image.
Until the FMOD situation is resolved I do not think it would be a good idea to merge this branch onto sprint, as it would stop all progress on everything else.

**Review by BigDub — COMMENTED** [review]
We can add the FMOD plugin to the .uproject file and set enabled to false. It will then not bother anyone opening the project without FMOD, nor secretly add itself again.
The problem is that this branch now has code in execution that relies on the FMOD plugin. Running this branch without the FMOD plugin installed will invariably crash.
We need to decide what we want to do with the FMOD plugin. I still do not understand the advantages it brings but if you want to use it I don't have any issue with it, assuming it doesn't create problems, which as I mentioned earlier it definitely would right now.
If we're going to use FMOD I think we ought to get it installed on every machine. I do not know how feasible this is. How large is the FMOD plugin? I would imagine it is not unwieldy. We should look into getting the CSRs to add it to the lab's image.
Until that situation is resolved however, I think it would be a very bad idea to merge this branch into the sprint branch as it would halt all progress on everything else.
Get back to me on details about FMOD: the features that make you want to use it, it's size, and the steps to install it.

**Pull request merged**
